### create playlist
POST http://localhost:8080/playlists
Content-Type: application/json

{
  "name": "",
  "description": "",
  "userId": 7,
  "workoutId": 77,
  "workoutType": "JOGA"
}

### get all playlists
GET http://localhost:8080/playlists/all

### get playlist by id
GET http://localhost:8080/playlists/20

### delete playlist
DELETE http://localhost:8080/playlists/1