### create workout
POST http://localhost:8080/workouts
Content-Type: application/json

{
  "type": "Zumba",
  "intensity": "5"
}

### get all workouts
GET http://localhost:8080/workouts/all

### get workout by id
GET http://localhost:8080/workouts/1

### update workout
PUT http://localhost:8080/workouts/1
Content-Type: application/json

{
  "id": "1",
  "type": "Zumba",
  "intensity": "6"
}

### delete workout
DELETE http://localhost:8080/workouts/1